import React, { useState, useRef, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import api from '../api/client';

export default function ChatWidget() {
  const { user, isAuthenticated, analysisResult } = useAuth();
  const navigate = useNavigate();

  const [isOpen, setIsOpen] = useState(false);
  const [isMaximized, setIsMaximized] = useState(false);
  const [dimensions, setDimensions] = useState({ width: 450, height: 630 });
  const [inputMessage, setInputMessage] = useState('');
  const [attachedImage, setAttachedImage] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState(null);

  const fileInputRef = useRef(null);
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);
  const isResizingRef = useRef(false);

  const userName = user?.full_name ? user.full_name.split(' ')[0] : 'Member';
  const fullName = user?.full_name || 'Verified Member';
  const skinType = analysisResult?.skin_type || user?.skin_type || 'Combination';
  const score = analysisResult?.overall_score || 90;
  const oiliness = analysisResult?.oiliness_level || 'Moderate';
  const redness = analysisResult?.redness_level || 'Low';
  const texture = analysisResult?.texture_level || 'Smooth';

  const [messages, setMessages] = useState([]);

  // Initialize personalized welcome when user/analysisResult is loaded
  useEffect(() => {
    if (messages.length === 0) {
      setMessages([
        {
          role: 'model',
          content: `Hello **${userName}**, welcome to Skiné AI.\n\nI have loaded your personalized skin scan data for **${fullName}**.\n\nYou may ask me about active ingredient compatibility, routine sequencing, paste product labels, or request direct product store links.\n\n*Disclaimer: Responses are generated by AI for informational guidance only and are not 100% accurate. For medical diagnoses, please consult a certified dermatologist.*`,
          time: 'Just now',
        },
      ]);
    }
  }, [user, analysisResult]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    if (isOpen) {
      scrollToBottom();
      setTimeout(() => inputRef.current?.focus(), 150);
    }
  }, [isOpen, messages, attachedImage]);

  // Listen for external trigger from Results page pills
  useEffect(() => {
    const handleExternalPrompt = (event) => {
      const promptText = event.detail?.prompt;
      if (promptText) {
        setIsOpen(true);
        if (isAuthenticated) {
          sendMessage(promptText);
        }
      }
    };

    window.addEventListener('open-skine-chat', handleExternalPrompt);
    return () => window.removeEventListener('open-skine-chat', handleExternalPrompt);
  }, [messages, isAuthenticated, analysisResult]);

  // Clipboard Paste Image Listener
  const handlePaste = (e) => {
    const items = e.clipboardData?.items;
    if (!items) return;
    for (let i = 0; i < items.length; i++) {
      if (items[i].type.indexOf('image') !== -1) {
        const file = items[i].getAsFile();
        if (file) {
          const reader = new FileReader();
          reader.onload = (event) => {
            setAttachedImage(event.target.result);
          };
          reader.readAsDataURL(file);
          e.preventDefault();
          break;
        }
      }
    }
  };

  const handleFileChange = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        setAttachedImage(event.target.result);
      };
      reader.readAsDataURL(file);
    }
    e.target.value = '';
  };

  // Interactive Seamless Resizing handlers
  const startResize = useCallback((direction, e) => {
    e.preventDefault();
    isResizingRef.current = true;
    const startX = e.clientX;
    const startY = e.clientY;
    const startWidth = dimensions.width;
    const startHeight = dimensions.height;

    const onMouseMove = (moveEvent) => {
      if (!isResizingRef.current) return;
      const deltaX = startX - moveEvent.clientX; // Dragging left increases width
      const deltaY = startY - moveEvent.clientY; // Dragging up increases height

      setDimensions((prev) => {
        let newWidth = prev.width;
        let newHeight = prev.height;

        if (direction === 'nw' || direction === 'w') {
          newWidth = Math.min(
            Math.max(340, startWidth + deltaX),
            window.innerWidth - 36
          );
        }
        if (direction === 'nw' || direction === 'n') {
          newHeight = Math.min(
            Math.max(420, startHeight + deltaY),
            window.innerHeight - 50
          );
        }

        return { width: newWidth, height: newHeight };
      });
      setIsMaximized(false);
    };

    const onMouseUp = () => {
      isResizingRef.current = false;
      window.removeEventListener('mousemove', onMouseMove);
      window.removeEventListener('mouseup', onMouseUp);
    };

    window.addEventListener('mousemove', onMouseMove);
    window.addEventListener('mouseup', onMouseUp);
  }, [dimensions]);

  const toggleMaximize = () => {
    setIsMaximized(!isMaximized);
  };

  const clinicalQuestions = [
    'Where can I buy a gentle cleanser for my skin?',
    'Impact of sebum level on barrier function',
    'Niacinamide and Vitamin C layering compatibility',
    'Recommended photoprotection formula with purchase link',
    'Cost-effective clinical alternatives for my routine',
    'Active retinoid titration schedule',
  ];

  const sendMessage = async (textToSend) => {
    const msg = textToSend || inputMessage;
    if ((!msg.trim() && !attachedImage) || isLoading) return;

    if (!isAuthenticated) {
      setIsOpen(true);
      return;
    }

    const currentImg = attachedImage;
    const userMsgObj = {
      role: 'user',
      content: msg.trim() || 'Analyze attached product image',
      image: currentImg,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    const updatedHistory = [...messages, userMsgObj];
    setMessages(updatedHistory);
    setInputMessage('');
    setAttachedImage(null);
    setIsLoading(true);

    try {
      const response = await api.post('/api/chat', {
        message: msg.trim(),
        image: currentImg,
        history: updatedHistory.map((m) => ({ role: m.role, content: m.content })),
        context: analysisResult || {},
      });

      if (response.data && response.data.success) {
        setMessages((prev) => [
          ...prev,
          {
            role: 'model',
            content: response.data.reply,
            model: response.data.model,
            time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          },
        ]);
      } else {
        if (response.data?.require_login) {
          setIsOpen(true);
        } else if (response.data?.quota_exceeded) {
          setMessages((prev) => [
            ...prev,
            {
              role: 'model',
              content: response.data.message,
              time: 'Just now',
            },
          ]);
        } else {
          setMessages((prev) => [
            ...prev,
            {
              role: 'model',
              content: response.data?.message || 'The AI service is temporarily unavailable. Please retry your inquiry.',
              time: 'Just now',
            },
          ]);
        }
      }
    } catch (err) {
      if (err.response?.status === 401) {
        setIsOpen(true);
      } else if (err.response?.status === 429) {
        setMessages((prev) => [
          ...prev,
          {
            role: 'model',
            content: 'Daily consultation quota reached (350 inquiries / 24 hours). Quota resets automatically in 24 hours.',
            time: 'Just now',
          },
        ]);
      } else {
        setMessages((prev) => [
          ...prev,
          {
            role: 'model',
            content: `For **${skinType}** skin, ensure non-comedogenic hydration and daily broad-spectrum SPF 50. Please re-submit your inquiry if the network was interrupted.`,
            time: 'Just now',
          },
        ]);
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const copyToClipboard = (text, idx) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(idx);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const renderFormattedText = (text) => {
    if (!text) return '';
    const lines = text.split('\n');
    return lines.map((line, idx) => {
      const trimmed = line.trim();
      if (!trimmed) return <div key={idx} style={{ height: '4px' }} />;

      // Markdown Headers (### Heading or ## Heading)
      if (trimmed.startsWith('### ') || trimmed.startsWith('## ')) {
        const headerText = trimmed.replace(/^#{2,3}\s*/, '');
        return (
          <div key={idx} className="fw-bold mt-2 mb-1" style={{ fontSize: '0.94rem' }}>
            {headerText}
          </div>
        );
      }

      // Markdown Links [Text](URL) -> Clickable <a target="_blank">
      let formattedLine = trimmed.replace(
        /\[([^\]]+)\]\((https?:\/\/[^\s\)]+)\)/g,
        '<a href="$2" target="_blank" rel="noopener noreferrer" class="chat-external-link"><i class="fa-solid fa-arrow-up-right-from-square me-1"></i>$1</a>'
      );

      // Markdown Bold Replacement
      formattedLine = formattedLine.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');

      // Markdown Bullets
      if (trimmed.startsWith('• ') || trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        return (
          <li
            key={idx}
            className="mb-1"
            style={{ marginLeft: '16px' }}
            dangerouslySetInnerHTML={{ __html: formattedLine.replace(/^[•\-\*]\s*/, '') }}
          />
        );
      }

      return (
        <p
          key={idx}
          className="mb-1"
          dangerouslySetInnerHTML={{ __html: formattedLine }}
        />
      );
    });
  };

  const cardStyle = isMaximized
    ? {
        width: 'min(820px, calc(100vw - 36px))',
        height: 'min(860px, calc(100vh - 48px))',
        transition: 'width 0.25s ease, height 0.25s ease',
      }
    : {
        width: `${dimensions.width}px`,
        height: `${dimensions.height}px`,
      };

  return (
    <div className="skine-chat-container">
      {/* Hidden File Input */}
      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileChange}
        accept="image/*"
        style={{ display: 'none' }}
      />

      {/* FLOATING LAUNCHER BUTTON */}
      {!isOpen && (
        <button
          className="skine-chat-launcher shadow-md"
          onClick={() => setIsOpen(true)}
          aria-label="Open Skiné AI Skincare Assistant"
          title="Open Skiné AI Skincare Assistant"
        >
          <div className="skine-launcher-pill">
            <div className="launcher-sparkle-wrap">
              <i className="fa-solid fa-wand-magic-sparkles launcher-icon"></i>
            </div>
            <div className="launcher-text-wrap d-none d-sm-flex">
              <span className="launcher-title">Skiné AI</span>
              <span className="launcher-sub">
                {isAuthenticated ? `Skincare Assistant for ${userName}` : 'AI Skincare Assistant'}
              </span>
            </div>
          </div>
          <span className="pulse-ring"></span>
        </button>
      )}

      {/* ADJUSTABLE EXPANDABLE CHAT PANEL */}
      {isOpen && (
        <div
          className={`skine-chat-card shadow-lg ${isMaximized ? 'is-maximized' : ''}`}
          style={cardStyle}
          onPaste={handlePaste}
        >
          {/* Seamless Edge & Corner Resize Triggers (No Clunky Boxes) */}
          {!isMaximized && (
            <>
              <div
                className="chat-resize-edge-top"
                onMouseDown={(e) => startResize('n', e)}
                title="Drag edge to resize height"
              />
              <div
                className="chat-resize-edge-left"
                onMouseDown={(e) => startResize('w', e)}
                title="Drag edge to resize width"
              />
              <div
                className="chat-resize-edge-corner"
                onMouseDown={(e) => startResize('nw', e)}
                title="Drag corner to resize"
              />
            </>
          )}

          {/* Header with Grab Bar */}
          <div className="skine-chat-header">
            {/* Elegant iOS-style Top Grab Handle */}
            {!isMaximized && (
              <div
                className="chat-grab-bar-wrap"
                onMouseDown={(e) => startResize('n', e)}
                title="Drag to adjust height"
              >
                <span className="chat-grab-bar"></span>
              </div>
            )}

            <div className="d-flex align-items-center justify-content-between">
              <div className="d-flex align-items-center gap-3">
                <div className="chat-avatar-circle">
                  <i className="fa-solid fa-wand-magic-sparkles"></i>
                </div>
                <div>
                  <h6 className="mb-0 fw-bold chat-title">Skiné AI Assistant</h6>
                  <div className="d-flex align-items-center gap-2 mt-1">
                    <span className="status-dot"></span>
                    <span className="chat-subtitle">AI Multimodal Skincare Assistant</span>
                  </div>
                </div>
              </div>

              <div className="d-flex align-items-center gap-2">
                {/* Maximize / Restore Toggle */}
                <button
                  className="chat-header-btn"
                  onClick={toggleMaximize}
                  title={isMaximized ? 'Restore standard size' : 'Expand / Maximize card'}
                >
                  <i
                    className={`fa-solid ${
                      isMaximized
                        ? 'fa-compress'
                        : 'fa-expand'
                    }`}
                  ></i>
                </button>

                {isAuthenticated && (
                  <button
                    className="chat-header-btn"
                    onClick={() =>
                      setMessages([
                        {
                          role: 'model',
                          content: `Welcome back, **${userName}**. I am ready to assist with your skincare inquiries for **${skinType}** skin.\n\n*Disclaimer: AI-generated responses are for informational guidance and are not 100% accurate.*`,
                          time: 'Just now',
                        },
                      ])
                    }
                    title="Reset conversation"
                  >
                    <i className="fa-solid fa-rotate-right"></i>
                  </button>
                )}
                <button
                  className="chat-header-btn"
                  onClick={() => setIsOpen(false)}
                  title="Minimize window"
                >
                  <i className="fa-solid fa-minus"></i>
                </button>
              </div>
            </div>
          </div>

          {/* AUTHENTICATION LOCK GATE */}
          {!isAuthenticated ? (
            <div className="skine-auth-lock-card">
              <div className="auth-lock-icon-wrap mb-3">
                <i className="fa-solid fa-shield-halved fa-2xl"></i>
              </div>
              <h5 className="fw-bold mb-2" style={{ color: 'var(--green-dark)' }}>
                Sign In Required
              </h5>
              <p className="text-muted mb-4 px-3" style={{ lineHeight: '1.6', fontSize: '0.88rem' }}>
                Skiné AI computes formulation, active ingredient compatibility, and product suggestions based on your personal skin scan profile. Please sign in to begin your consultation.
              </p>

              <div className="d-flex flex-column gap-2 w-100 px-4">
                <button
                  className="hero-btn w-100 justify-content-center py-2"
                  onClick={() => {
                    setIsOpen(false);
                    navigate('/login', { state: { from: { pathname: window.location.pathname } } });
                  }}
                >
                  <i className="fa-solid fa-right-to-bracket me-2"></i> Sign In to Account
                </button>
                <button
                  className="hero-btn-outline w-100 justify-content-center py-2"
                  onClick={() => {
                    setIsOpen(false);
                    navigate('/register');
                  }}
                >
                  <i className="fa-solid fa-user-plus me-2"></i> Register New Profile
                </button>
              </div>
            </div>
          ) : (
            <>
              {/* Patient Diagnostic Banner (Addressing User & Scan Details) */}
              <div className="chat-patient-banner">
                <div className="d-flex align-items-center justify-content-between mb-2">
                  <div className="d-flex align-items-center gap-2">
                    <i className="fa-solid fa-id-card-clip text-muted"></i>
                    <span className="fw-bold text-dark" style={{ fontSize: '0.84rem' }}>
                      {fullName}
                    </span>
                  </div>
                  <span className="badge-skin-type">{skinType} Skin</span>
                </div>

                <div className="patient-biomarker-grid">
                  <div className="biomarker-pill">
                    <span className="bio-label">Health Index</span>
                    <span className="bio-val">{score}%</span>
                  </div>
                  <div className="biomarker-pill">
                    <span className="bio-label">Sebum</span>
                    <span className="bio-val">{oiliness}</span>
                  </div>
                  <div className="biomarker-pill">
                    <span className="bio-label">Erythema</span>
                    <span className="bio-val">{redness}</span>
                  </div>
                  <div className="biomarker-pill">
                    <span className="bio-label">Texture</span>
                    <span className="bio-val">{texture}</span>
                  </div>
                </div>
              </div>

              {/* Messages Body */}
              <div className="skine-chat-body">
                {messages.map((msg, index) => (
                  <div
                    key={index}
                    className={`chat-message-row ${msg.role === 'user' ? 'user-row' : 'bot-row'}`}
                  >
                    {msg.role === 'model' && (
                      <div className="bot-avatar-mini">
                        <i className="fa-solid fa-wand-magic-sparkles"></i>
                      </div>
                    )}
                    <div className={`chat-bubble ${msg.role === 'user' ? 'user-bubble' : 'bot-bubble'}`}>
                      {msg.image && (
                        <div className="chat-msg-img-container mb-2">
                          <img src={msg.image} alt="Uploaded product/skin" className="chat-msg-img" />
                        </div>
                      )}
                      <div className="chat-text-content">{renderFormattedText(msg.content)}</div>
                      {msg.role === 'model' ? (
                        <div className="d-flex align-items-center justify-content-between mt-2 pt-2 border-top border-opacity-10 gap-2">
                          <button
                            className="chat-copy-btn"
                            onClick={() => copyToClipboard(msg.content, index)}
                            title="Copy response"
                          >
                            <i className={`fa-regular ${copiedIndex === index ? 'fa-check text-success' : 'fa-copy'}`}></i>
                            <span className="ms-1">{copiedIndex === index ? 'Copied' : 'Copy'}</span>
                          </button>
                          <div className="chat-time-tag ms-auto">{msg.time}</div>
                        </div>
                      ) : (
                        <div className="chat-time-tag text-end mt-1">{msg.time}</div>
                      )}
                    </div>
                  </div>
                ))}

                {isLoading && (
                  <div className="chat-message-row bot-row">
                    <div className="bot-avatar-mini">
                      <i className="fa-solid fa-wand-magic-sparkles"></i>
                    </div>
                    <div className="chat-bubble bot-bubble typing-bubble">
                      <span className="typing-dot"></span>
                      <span className="typing-dot"></span>
                      <span className="typing-dot"></span>
                    </div>
                  </div>
                )}
                <div ref={messagesEndRef} />
              </div>

              {/* Clinical Suggested Inquiry Pills */}
              <div className="skine-chat-chips">
                {clinicalQuestions.map((q, idx) => (
                  <button
                    key={idx}
                    className="chat-chip-btn"
                    onClick={() => sendMessage(q)}
                    disabled={isLoading}
                  >
                    {q}
                  </button>
                ))}
              </div>

              {/* Input Footer */}
              <div className="skine-chat-footer">
                {/* Image Attachment Preview Strip */}
                {attachedImage && (
                  <div className="chat-image-preview-bar">
                    <div className="d-flex align-items-center gap-2">
                      <img src={attachedImage} alt="Attachment preview" className="chat-preview-thumb" />
                      <span className="chat-preview-text">Image ready for formulation analysis (Ctrl+V supported)</span>
                    </div>
                    <button
                      className="chat-preview-remove-btn"
                      onClick={() => setAttachedImage(null)}
                      title="Remove image"
                    >
                      <i className="fa-solid fa-xmark"></i>
                    </button>
                  </div>
                )}

                <div className="chat-input-wrapper">
                  {/* Upload Image Button */}
                  <button
                    type="button"
                    className="chat-upload-btn"
                    onClick={() => fileInputRef.current?.click()}
                    title="Upload or paste product label image"
                    disabled={isLoading}
                  >
                    <i className="fa-solid fa-image"></i>
                  </button>

                  <input
                    ref={inputRef}
                    type="text"
                    className="form-control chat-input"
                    placeholder="Ask a question or paste an image/label (Ctrl+V)..."
                    value={inputMessage}
                    onChange={(e) => setInputMessage(e.target.value)}
                    onKeyDown={handleKeyDown}
                    disabled={isLoading}
                  />
                  <button
                    className="chat-send-btn"
                    onClick={() => sendMessage()}
                    disabled={(!inputMessage.trim() && !attachedImage) || isLoading}
                    aria-label="Send inquiry"
                    title="Send inquiry"
                  >
                    <i className="fa-solid fa-arrow-up"></i>
                  </button>
                </div>
                <div className="text-center mt-2">
                  <span className="chat-disclaimer">
                    AI-generated responses · Click links to view verified stores · Informational guidance only
                  </span>
                </div>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
}
